jobs:
  run:
    name: Check
    runs-on: ubuntu-20.04

    steps:
      - name: Begin
        uses: actions/checkout@v2
      - name: Install Deps
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Unit Tests
        run: ./run/action

name: Run

on:
  schedule:
    - cron: "40 */6 * * *"
